
server.port: ${PORT:8080}

logging.level: 
  root: info
  org.atmosphere: warn

vaadin.allowed-packages: com.vaadin,org.vaadin,org.eclipse,graphql

logging.level.org.atmosphere: warn

spring:
  graphql:
    graphiql:
      enabled=true
